/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddNoteInput { 'note' : string, 'leadId' : string }
export interface CreateLeadInput {
  'name' : string,
  'email' : string,
  'company' : [] | [string],
}
export interface Lead {
  'id' : string,
  'status' : LeadStatus,
  'name' : string,
  'lastUpdated' : Time,
  'createdTime' : Time,
  'email' : string,
  'company' : [] | [string],
  'notes' : Array<string>,
}
export type LeadStatus = { 'new' : null } |
  { 'won' : null } |
  { 'lost' : null } |
  { 'proposalSent' : null } |
  { 'contacted' : null } |
  { 'negotiation' : null } |
  { 'qualified' : null };
export type Time = bigint;
export interface UpdateStatusInput {
  'leadId' : string,
  'newStatus' : LeadStatus,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLeadNote' : ActorMethod<[AddNoteInput], [] | [Lead]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLead' : ActorMethod<[CreateLeadInput], string>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLead' : ActorMethod<[string], Lead>,
  'getLeadCreator' : ActorMethod<[string], string>,
  'getLeadTimeline' : ActorMethod<[string], [Time, Time]>,
  'getLeadsByStatus' : ActorMethod<[LeadStatus], Array<Lead>>,
  'getTotalLeads' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLeadStatus' : ActorMethod<[UpdateStatusInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];