/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddNoteInput = IDL.Record({
  'note' : IDL.Text,
  'leadId' : IDL.Text,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'won' : IDL.Null,
  'lost' : IDL.Null,
  'proposalSent' : IDL.Null,
  'contacted' : IDL.Null,
  'negotiation' : IDL.Null,
  'qualified' : IDL.Null,
});
export const Time = IDL.Int;
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'status' : LeadStatus,
  'name' : IDL.Text,
  'lastUpdated' : Time,
  'createdTime' : Time,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'notes' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateLeadInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
});
export const UpdateStatusInput = IDL.Record({
  'leadId' : IDL.Text,
  'newStatus' : LeadStatus,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLeadNote' : IDL.Func([AddNoteInput], [IDL.Opt(Lead)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLead' : IDL.Func([CreateLeadInput], [IDL.Text], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLead' : IDL.Func([IDL.Text], [Lead], ['query']),
  'getLeadCreator' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getLeadTimeline' : IDL.Func([IDL.Text], [Time, Time], ['query']),
  'getLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(Lead)], ['query']),
  'getTotalLeads' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLeadStatus' : IDL.Func([UpdateStatusInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddNoteInput = IDL.Record({ 'note' : IDL.Text, 'leadId' : IDL.Text });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'won' : IDL.Null,
    'lost' : IDL.Null,
    'proposalSent' : IDL.Null,
    'contacted' : IDL.Null,
    'negotiation' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const Time = IDL.Int;
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'status' : LeadStatus,
    'name' : IDL.Text,
    'lastUpdated' : Time,
    'createdTime' : Time,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'notes' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateLeadInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
  });
  const UpdateStatusInput = IDL.Record({
    'leadId' : IDL.Text,
    'newStatus' : LeadStatus,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLeadNote' : IDL.Func([AddNoteInput], [IDL.Opt(Lead)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLead' : IDL.Func([CreateLeadInput], [IDL.Text], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLead' : IDL.Func([IDL.Text], [Lead], ['query']),
    'getLeadCreator' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getLeadTimeline' : IDL.Func([IDL.Text], [Time, Time], ['query']),
    'getLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(Lead)], ['query']),
    'getTotalLeads' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLeadStatus' : IDL.Func([UpdateStatusInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };