/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lead {
    id: string;
    status: LeadStatus;
    name: string;
    lastUpdated: Time;
    createdTime: Time;
    email: string;
    company?: string;
    notes: Array<string>;
}
export type Time = bigint;
export interface CreateLeadInput {
    name: string;
    email: string;
    company?: string;
}
export interface AddNoteInput {
    note: string;
    leadId: string;
}
export interface UserProfile {
    name: string;
    email: string;
    company?: string;
}
export interface UpdateStatusInput {
    leadId: string;
    newStatus: LeadStatus;
}
export enum LeadStatus {
    new_ = "new",
    won = "won",
    lost = "lost",
    proposalSent = "proposalSent",
    contacted = "contacted",
    negotiation = "negotiation",
    qualified = "qualified"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLeadNote(input: AddNoteInput): Promise<Lead | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createLead(input: CreateLeadInput): Promise<string>;
    getAllLeads(): Promise<Array<Lead>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLead(leadId: string): Promise<Lead>;
    getLeadCreator(leadId: string): Promise<string>;
    getLeadTimeline(leadId: string): Promise<[Time, Time]>;
    getLeadsByStatus(status: LeadStatus): Promise<Array<Lead>>;
    getTotalLeads(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateLeadStatus(input: UpdateStatusInput): Promise<void>;
}
import type { CreateLeadInput as _CreateLeadInput, Lead as _Lead, LeadStatus as _LeadStatus, Time as _Time, UpdateStatusInput as _UpdateStatusInput, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLeadNote(arg0: AddNoteInput): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeadNote(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeadNote(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createLead(arg0: CreateLeadInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(to_candid_CreateLeadInput_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(to_candid_CreateLeadInput_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: string): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_Lead_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_Lead_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadCreator(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadCreator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadCreator(arg0);
            return result;
        }
    }
    async getLeadTimeline(arg0: string): Promise<[Time, Time]> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadTimeline(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadTimeline(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getLeadsByStatus(arg0: LeadStatus): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByStatus(to_candid_LeadStatus_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByStatus(to_candid_LeadStatus_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalLeads(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalLeads();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLeadStatus(arg0: UpdateStatusInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStatus(to_candid_UpdateStatusInput_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStatus(to_candid_UpdateStatusInput_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_LeadStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : from_candid_Lead_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    company: [] | [string];
}): {
    name: string;
    email: string;
    company?: string;
} {
    return {
        name: value.name,
        email: value.email,
        company: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.company))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _LeadStatus;
    name: string;
    lastUpdated: _Time;
    createdTime: _Time;
    email: string;
    company: [] | [string];
    notes: Array<string>;
}): {
    id: string;
    status: LeadStatus;
    name: string;
    lastUpdated: Time;
    createdTime: Time;
    email: string;
    company?: string;
    notes: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n4(_uploadFile, _downloadFile, value.status),
        name: value.name,
        lastUpdated: value.lastUpdated,
        createdTime: value.createdTime,
        email: value.email,
        company: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.company)),
        notes: value.notes
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    won: null;
} | {
    lost: null;
} | {
    proposalSent: null;
} | {
    contacted: null;
} | {
    negotiation: null;
} | {
    qualified: null;
}): LeadStatus {
    return "new" in value ? LeadStatus.new : "won" in value ? LeadStatus.won : "lost" in value ? LeadStatus.lost : "proposalSent" in value ? LeadStatus.proposalSent : "contacted" in value ? LeadStatus.contacted : "negotiation" in value ? LeadStatus.negotiation : "qualified" in value ? LeadStatus.qualified : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n2(_uploadFile, _downloadFile, x));
}
function to_candid_CreateLeadInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLeadInput): _CreateLeadInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateStatusInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStatusInput): _UpdateStatusInput {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    company?: string;
}): {
    name: string;
    email: string;
    company: [] | [string];
} {
    return {
        name: value.name,
        email: value.email,
        company: value.company ? candid_some(value.company) : candid_none()
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leadId: string;
    newStatus: LeadStatus;
}): {
    leadId: string;
    newStatus: _LeadStatus;
} {
    return {
        leadId: value.leadId,
        newStatus: to_candid_LeadStatus_n17(_uploadFile, _downloadFile, value.newStatus)
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    new: null;
} | {
    won: null;
} | {
    lost: null;
} | {
    proposalSent: null;
} | {
    contacted: null;
} | {
    negotiation: null;
} | {
    qualified: null;
} {
    return value == LeadStatus.new ? {
        new_: null
    } : value == LeadStatus.won ? {
        won: null
    } : value == LeadStatus.lost ? {
        lost: null
    } : value == LeadStatus.proposalSent ? {
        proposalSent: null
    } : value == LeadStatus.contacted ? {
        contacted: null
    } : value == LeadStatus.negotiation ? {
        negotiation: null
    } : value == LeadStatus.qualified ? {
        qualified: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
